### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by RikkaW** [RikkaW/FCM-for-Mojo#1]
- [ ]  本地的黑白名单
- [ ]  直接将 token 交给服务端

**Comment by kotomei** [comment]
补充几条个人认为有需求的点（
- [ ] 免推送时段
- [ ] 通知回复后依旧可见

**Comment by GongJianwei** [comment]
[ ] 可自定义的通知呼吸灯
[ ] 自动更新好友头像
[ ] 阅读后更改成已读状态

**Comment by RikkaW** [comment]
@GongJianwei
阅读后更改成已读状态 这个是做不到的..
自动更新好友头像 这个要怎么自动呢..

**Comment by GongJianwei** [comment]
@RikkaW 理想状态：服务器收到消息时，自动检测头像是否更变，如更变就向客户端发送刷新请求
现实：客户端一段时间内自动刷新
我也知道改为已读状态几乎是不可能由本项目实现的……现在这个理想状态我也觉得无法实现

**Comment by simonsmh** [comment]
[ ] 内建的可简易发起会话/消息记录功能（界面类似aosp的联系人/短信这样的
[ ] 接到登录通知后，自动将登录qr code从图床下载到本机

**Comment by kotomei** [comment]
@simonsmh 我来上传 Perl mod 吧，手头有 Push 权限的

**Comment by simonsmh** [comment]
好吧（
或许还是先发个pr比较好？

kotomei zhang <notifications@github.com>于2017年4月28日周五 17:27写道：

**Comment by Konglolin** [comment]
v0.1.1多信息通知有些问题，新通知会吃掉旧通知QwQ

**Comment by GongJianwei** [comment]
@simonsmh 这已经相当于做一个简易的 QQ 了，会不会因为触动腾讯的利益而导致本项目遭到封杀？

**Comment by simonsmh** [comment]
怎么会啊
原本gcmmojo也有这个功能的，但ui难看使用不方便

没有字的回音 <notifications@github.com>于2017年4月29日周六 11:29写道：

**Comment by GongJianwei** [comment]
@simonsmh 我觉得要从利益方面上分析这个问题，当然本项目也不应该因为这个问题作茧自缚

**Comment by simonsmh** [comment]
我觉得要看rikka够不够懒🤣（
mojo-webqq自身使用的就是腾讯自家的api，本身作为客户端就局限很大（不能收发图之类的），真要有限制早就关了

没有字的回音 <notifications@github.com>于2017年4月29日周六 11:37写道：

**Comment by guozy2001** [comment]
- [ ] 群消息与好友消息分成两张卡片推送 （或许能解决不同优先级时消息无法弹出的问题）；

- [ ] 在QQ前台运行时不显示通知，但仍开启提示音/振动；

**Comment by GongJianwei** [comment]
- [ ] 在 Wiki 中写明「特权 API 服务」的用法

**Comment by simonsmh** [comment]
nginx 有自带的 perl 模块，能否做些什么？

**Comment by WordlessEcho** [comment]
@simonsmh 第一次听说 Nginx 有这个东西，当然我也看到它是实验性的
[Module ngx_http_perl_module](http://nginx.org/en/docs/http/ngx_http_perl_module.html)

**Comment by WordlessEcho** [comment]
@simonsmh 
> It is thus recommended to perform only such operations that have predictable and short execution time, such as accessing the local file system.

**Comment by simonsmh** [comment]
root     16551   700  0 01:00 pts/5    00:02:43 perl start.pl

**Comment by WordlessEcho** [comment]
@simonsmh 这样的话，需要重编 Nginx，虽然可能不是很难，但并不是所有人都有编译环境
当然我认为这种方式是可行的，个人意见：作为一个备选项与 Node.js 一同开发

**Comment by simonsmh** [comment]
> 用的是 nginx-extras 预编译软件包

`apt install nginx-extras`
服了你了23333

**Comment by simonsmh** [comment]
我看到扣头妹在写dockerfile，我觉得docker用用nodejs倒是挺好的，但vps上已经挂上nginx的就没什么必要了

**Comment by WordlessEcho** [comment]
我又被 dalao 嘲讽了，好气啊
同时我似乎注意到了一点：CentOS 是没有这个包的

**Comment by kotomei** [comment]
> CentOS 是没有这个包的

~~所以说 CentOS 这种用着上古软件包的发行版还是丢掉为好~~

**Comment by WordlessEcho** [comment]
＠kotomei 在座的各位，只有你没有资格说这句话，教程里还用 CentOS 呢 (

**Comment by haruue** [comment]
emmc...所以考虑通用性的话....
~~其实作为 Arch Linux 用户我也不兹磁 CentOS 这种上古发行版~~

**Comment by simonsmh** [comment]
http://nginx.org/en/linux_packages.html

**Comment by WordlessEcho** [comment]
各种黑魔法……吓人 ~~最后还是没搞懂 CentOS 怎么装~~

**Comment by simonsmh** [comment]
`wget http://nginx.org/keys/nginx_signing.key && sudo rpm --import nginx_signing.key`

edit /etc/yum.repos.d/nginx.repo
```
[nginx]
name=nginx repo
baseurl=http://nginx.org/packages/mainline/centos/OSRELEASE/$basearch/
gpgcheck=0
enabled=1
Replace “OSRELEASE” with “6” or “7”, for 6.x or 7.x versions, respectively.
```
npm install nginx-module-perl

**Comment by kotomei** [comment]
> npm install nginx-module-perl
应该需要加上 `-g` 吧（逃

**Comment by kkren** [comment]
- [ ] 选择需要推送的群

**Comment by WordlessEcho** [comment]
-[ ] 资源占用优化

**Comment by RikkaW** [comment]
@WordlessEcho 不能找 Rikka（
